### PR TITLE
Features

### PR DESCRIPTION
**Pull request by stanleySimeon**
# In this milestone I created:

  - a greeting rails-react app
  - create an API endpoint

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Stanley, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have an appropriate ReadMe. Kindly ensure that your ReadMe is detailed and reflects your project. I suggest you use this [recommended template](https://github.com/microverseinc/readme-template/blob/master/README.md). Kindly request for another review when fix is done.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by youmari — CHANGES_REQUESTED** [review]
Hi @stanleySimeon , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔️ PRO PR
✔️ Git flow 
✔️ NO linter error

## Required Changes ♻️

- [x] I've checked your PR all the requirements are implemented but when I tried to create a database on my local machine I got an error so please make sure to fix it in order for your app can run properly without error 
Screen Shot 2022-09-20 at 15 45 51

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by stanleySimeon** [comment]
@youmari, kindly can you precise what should change, please?
Because everything works perfectly on my side.

**Comment by youmari** [comment]
@stanleySimeon if it's working properly on your side please try to record a video where you show your project  working 
and all the requirements

**Comment by stanleySimeon** [comment]
> @stanleySimeon if it's working properly on your side please try to record a video where you show your project working and all the requirements

@youmari, this is a screenshot of my working project
Screen Shot 2022-09-20 at 16 49 26

**Review by omarsalem7 — APPROVED** [review]
Hi @stanleySimeon 😊, 
# STATUS: APPROVED! 🥇 💯 

giphy

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Descriptive pull request 
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
